# Use uma imagem base do Python
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# Comando para rodar a aplicação
CMD ["flask", "run", "--host=0.0.0.0"]